-- Create peer_transfer_details table for storing detailed information about transfers
CREATE TABLE public.peer_transfer_details (
  transfer_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  peertransfer_id BIGINT NOT NULL,
  transaction_type CHARACTER VARYING(50) NOT NULL, -- 'earn', 'redemption', 'p2p-sent', 'p2p-received', 'admin-added', 'admin-deducted'
  description TEXT NULL,
  subdescription TEXT NULL,
  quantity CHARACTER VARYING(100) NULL, -- e.g., '4 kg', '1 voucher', '3 bags', '1 transfer'
  reason CHARACTER VARYING(255) NULL, -- for admin adjustments: 'bonus', 'referral', 'penalty', 'adjustment', etc.
  status CHARACTER VARYING(50) NULL DEFAULT 'Completed', -- 'Pending', 'Completed', 'Failed'
  metadata JSONB NULL, -- store additional data as JSON (location, zone, category, etc.)
  created_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT peer_transfer_details_pkey PRIMARY KEY (transfer_detail_id),
  CONSTRAINT fk_peer_transfer_details_log FOREIGN KEY (peertransfer_id) REFERENCES public.peer_transfer_logs (peertransfer_id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Create indexes for performance
CREATE INDEX idx_peer_transfer_details_peertransfer_id ON public.peer_transfer_details(peertransfer_id);
CREATE INDEX idx_peer_transfer_details_transaction_type ON public.peer_transfer_details(transaction_type);
CREATE INDEX idx_peer_transfer_details_status ON public.peer_transfer_details(status);
CREATE INDEX idx_peer_transfer_details_created_at ON public.peer_transfer_details(created_at);

-- Create table comment for documentation
COMMENT ON TABLE public.peer_transfer_details IS 'Stores detailed information about peer transfers and admin adjustments for comprehensive auditing and transaction history';
COMMENT ON COLUMN public.peer_transfer_details.transaction_type IS 'Type of transaction: earn, redemption, p2p-sent, p2p-received, admin-added, admin-deducted';
COMMENT ON COLUMN public.peer_transfer_details.quantity IS 'Quantity/volume context (e.g., 4 kg, 1 voucher, 3 bags)';
COMMENT ON COLUMN public.peer_transfer_details.reason IS 'Reason for the transaction, especially for admin adjustments';
COMMENT ON COLUMN public.peer_transfer_details.metadata IS 'Additional structured data stored as JSON (location, zone, category, etc.)';
