-- Create peer_transfer_logs table
CREATE TABLE public.peer_transfer_logs (
  peertransfer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  system_id UUID NOT NULL,
  campus_id CHARACTER VARYING(50) NULL,
  from_email CHARACTER VARYING(255) NOT NULL,
  from_name CHARACTER VARYING(255) NULL,
  to_email CHARACTER VARYING(255) NOT NULL,
  to_name CHARACTER VARYING(255) NULL,
  log_time TIME WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIME,
  log_date DATE NULL DEFAULT CURRENT_DATE,
  points_transferred INTEGER NOT NULL,
  CONSTRAINT peer_transfer_logs_pkey PRIMARY KEY (peertransfer_id),
  CONSTRAINT fk_peer_transfer_logs_campus FOREIGN KEY (campus_id) REFERENCES user_accounts (campus_id) ON DELETE SET NULL,
  CONSTRAINT fk_peer_transfer_logs_user FOREIGN KEY (system_id) REFERENCES user_accounts (system_id) ON DELETE CASCADE,
  CONSTRAINT chk_peer_transfer_positive CHECK ((points_transferred > 0))
) TABLESPACE pg_default;

-- Create index for faster queries
CREATE INDEX idx_peer_transfer_logs_from_email ON public.peer_transfer_logs(from_email);
CREATE INDEX idx_peer_transfer_logs_to_email ON public.peer_transfer_logs(to_email);
CREATE INDEX idx_peer_transfer_logs_log_date ON public.peer_transfer_logs(log_date);
